services:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ex
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Arivu2001@
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  spring-app:
    build:
      context: ./backend-springboot
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/ex
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Arivu2001@
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db

  react-app:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - spring-app

volumes:
  postgres_data:
