name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydb
        ports:
          - 5432:5432

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK for Spring Boot
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Set up Node.js for React+Vite
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Build & Test Backend
      - name: Build & Test Spring Boot Backend
        working-directory: backend
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      # Build & Test Frontend
      - name: Install & Build React+Vite Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      # Deploy (Optional)
      - name: Deploy to Server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > deploy_key && chmod 600 deploy_key
          ssh -i deploy_key $SSH_USER@$SSH_HOST << 'EOF'
            cd /path/to/project
            git pull origin main
            docker-compose down
            docker-compose up --build -d
          EOF